export type BbsAiRequest = {
  prompt: string
  currentHtml?: string
}

export type BbsAiResponse = {
  html: string
  source: 'bbs-ai-model' | 'fallback'
}

type BbsAiModelResponse = {
  html?: string
  content?: string
  result?: string
}

const ENGINE_URL = process.env.BBS_AI_ENGINE_URL

function cleanHtml(value: string): string {
  let html = String(value || '').trim()

  // Remove markdown code fences if a model accidentally returns them.
  html = html.replace(/^```html\s*/i, '')
  html = html.replace(/^```HTML\s*/i, '')
  html = html.replace(/^```\s*/i, '')
  html = html.replace(/\s*```$/i, '')

  html = html.trim()

  const doctypeIndex = html.toLowerCase().indexOf('<!doctype')
  const htmlIndex = html.toLowerCase().indexOf('<html')

  if (doctypeIndex >= 0) {
    html = html.slice(doctypeIndex)
  } else if (htmlIndex >= 0) {
    html = `<!doctype html>\n${html.slice(htmlIndex)}`
  }

  return html.trim()
}

function isValidWebsite(html: string): boolean {
  const value = html.toLowerCase()

  return (
    value.includes('<!doctype html>') &&
    value.includes('<html') &&
    value.includes('<head') &&
    value.includes('<body') &&
    value.includes('</html>')
  )
}

function websiteSystemPrompt(): string {
  return `
You are BBS AI, the website-generation intelligence behind Better Brand Services.

Your job is to transform a user's natural-language website request into a complete,
professional, production-quality website.

You are NOT generating an explanation.

You are generating the actual website.

RULES:

1. Return ONLY complete raw HTML.
2. The document MUST begin with <!doctype html>.
3. Include <html>, <head>, and <body>.
4. Put all CSS inside <style>.
5. Put JavaScript inside <script>.
6. Do not use Markdown.
7. Do not use code fences.
8. Do not explain your answer.
9. Make the website responsive.
10. Make the design look professional and intentional.
11. Use semantic HTML.
12. Use accessible buttons, links, labels, and headings.
13. Create realistic content based on the user's request.
14. Do not mention that the website was generated by an AI unless the user specifically asks.
15. Do not automatically use "Better Brand Services" as the website's brand.
16. The user's requested business, person, organization, product, or idea should be the focus.
17. Use the user's requested colors, style, industry, audience, and features.
18. If the user asks for a specific section, actually implement it.
19. If the user asks for forms, create functional front-end forms.
20. If the user asks for navigation, make the navigation work.
21. If the user asks for animations, implement tasteful CSS/JavaScript animations.
22. If images are appropriate, use reliable remote image URLs or visually appealing CSS placeholders.
23. Never return placeholder text such as "Lorem ipsum".
24. Never return a generic BBS template when the user gave a specific request.
25. Generate a complete website, not a partial snippet.

Think through the website structure before generating it.

The final response must contain ONLY the HTML document.
`
}

function fallbackWebsite(prompt: string): string {
  const text = prompt.toLowerCase()

  let title = 'Your New Website'
  let subtitle = 'A modern website built around your idea.'
  let category = 'Website'

  if (
    text.includes('restaurant') ||
    text.includes('food') ||
    text.includes('cafe') ||
    text.includes('coffee')
  ) {
    title = 'Modern Dining'
    subtitle = 'Great food, memorable experiences, and a place worth visiting.'
    category = 'Restaurant'
  } else if (
    text.includes('portfolio') ||
    text.includes('developer') ||
    text.includes('designer')
  ) {
    title = 'Creative Portfolio'
    subtitle = 'A professional showcase for ideas, projects, and creative work.'
    category = 'Portfolio'
  } else if (
    text.includes('gym') ||
    text.includes('fitness') ||
    text.includes('workout')
  ) {
    title = 'Peak Fitness'
    subtitle = 'Train smarter, stay consistent, and reach your goals.'
    category = 'Fitness'
  } else if (
    text.includes('store') ||
    text.includes('shop') ||
    text.includes('clothing')
  ) {
    title = 'Modern Store'
    subtitle = 'Discover products selected for modern everyday life.'
    category = 'Store'
  } else if (
    text.includes('agency') ||
    text.includes('marketing') ||
    text.includes('business')
  ) {
    title = 'Modern Business'
    subtitle = 'Professional solutions designed to help your business grow.'
    category = 'Business'
  }

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>

  <style>
    * {
      box-sizing: border-box;
    }

    html {
      scroll-behavior: smooth;
    }

    body {
      margin: 0;
      font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #080b12;
      color: white;
    }

    nav {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      z-index: 10;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 7%;
      background: rgba(8, 11, 18, .75);
      backdrop-filter: blur(18px);
      border-bottom: 1px solid rgba(255,255,255,.08);
    }

    .logo {
      font-size: 20px;
      font-weight: 800;
    }

    nav a {
      color: #cbd5e1;
      text-decoration: none;
      margin-left: 25px;
    }

    .hero {
      min-height: 100vh;
      display: grid;
      place-items: center;
      text-align: center;
      padding: 130px 7% 80px;
      background:
        radial-gradient(circle at 20% 20%, rgba(59,130,246,.25), transparent 35%),
        radial-gradient(circle at 80% 70%, rgba(139,92,246,.22), transparent 35%);
    }

    .hero-inner {
      max-width: 900px;
    }

    .badge {
      display: inline-block;
      padding: 8px 14px;
      border: 1px solid rgba(255,255,255,.12);
      border-radius: 999px;
      color: #cbd5e1;
      margin-bottom: 25px;
    }

    h1 {
      font-size: clamp(52px, 9vw, 110px);
      line-height: .95;
      letter-spacing: -5px;
      margin: 0;
    }

    .subtitle {
      color: #a8b3c5;
      font-size: 20px;
      line-height: 1.7;
      max-width: 700px;
      margin: 30px auto;
    }

    .buttons {
      display: flex;
      justify-content: center;
      gap: 14px;
      flex-wrap: wrap;
    }

    .button {
      display: inline-block;
      padding: 15px 24px;
      border-radius: 12px;
      text-decoration: none;
      font-weight: 700;
    }

    .primary {
      background: white;
      color: #080b12;
    }

    .secondary {
      border: 1px solid rgba(255,255,255,.15);
      color: white;
    }

    section {
      padding: 100px 7%;
    }

    .container {
      max-width: 1100px;
      margin: auto;
    }

    h2 {
      font-size: clamp(36px, 5vw, 64px);
      margin-top: 0;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 20px;
    }

    .card {
      padding: 30px;
      border: 1px solid rgba(255,255,255,.08);
      border-radius: 20px;
      background: rgba(255,255,255,.04);
    }

    .card p {
      color: #9ca8ba;
      line-height: 1.7;
    }

    footer {
      padding: 35px 7%;
      color: #718096;
      border-top: 1px solid rgba(255,255,255,.08);
      text-align: center;
    }

    @media (max-width: 800px) {
      .grid {
        grid-template-columns: 1fr;
      }

      nav div:last-child {
        display: none;
      }
    }
  </style>
</head>

<body>

  <nav>
    <div class="logo">${category}</div>

    <div>
      <a href="#about">About</a>
      <a href="#features">Features</a>
      <a href="#contact">Contact</a>
    </div>
  </nav>

  <main>

    <section class="hero">
      <div class="hero-inner">

        <div class="badge">${category}</div>

        <h1>${title}</h1>

        <p class="subtitle">${subtitle}</p>

        <div class="buttons">
          <a class="button primary" href="#features">Get Started</a>
          <a class="button secondary" href="#contact">Learn More</a>
        </div>

      </div>
    </section>

    <section id="about">
      <div class="container">
        <h2>Built around your idea.</h2>

        <p class="subtitle">
          ${prompt.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
        </p>
      </div>
    </section>

    <section id="features">
      <div class="container">
        <h2>Everything you need.</h2>

        <div class="grid">
          <div class="card">
            <h3>Professional Design</h3>
            <p>A polished interface designed for modern users.</p>
          </div>

          <div class="card">
            <h3>Responsive</h3>
            <p>Works across phones, tablets, and desktop screens.</p>
          </div>

          <div class="card">
            <h3>Easy to Customize</h3>
            <p>The website structure can be expanded and modified.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <h2>Let's get started.</h2>

        <a class="button primary" href="mailto:hello@example.com">
          Contact Us
        </a>
      </div>
    </section>

  </main>

  <footer>
    © 2026 ${title}
  </footer>

</body>
</html>`
}

async function callBbsAiModel(
  request: BbsAiRequest,
): Promise<string> {
  if (!ENGINE_URL) {
    throw new Error(
      'BBS_AI_ENGINE_URL is not configured. The BBS AI model server has not been connected yet.',
    )
  }

  const response = await fetch(ENGINE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      system: websiteSystemPrompt(),
      prompt: request.prompt,
      currentHtml: request.currentHtml || '',
    }),
  })

  if (!response.ok) {
    const errorText = await response.text().catch(() => '')

    throw new Error(
      `BBS AI model request failed (${response.status}). ${errorText}`,
    )
  }

  const data = (await response.json()) as BbsAiModelResponse

  const html =
    data.html ||
    data.content ||
    data.result ||
    ''

  return cleanHtml(html)
}

export async function generateWithBbsAI(
  request: BbsAiRequest,
): Promise<BbsAiResponse> {
  /*
   * If the real BBS AI model server exists, use it.
   *
   * If it does not exist yet, use the local fallback so the
   * website builder continues working while we build the
   * actual BBS AI model infrastructure.
   */
  if (ENGINE_URL) {
    const html = await callBbsAiModel(request)

    if (!isValidWebsite(html)) {
      throw new Error(
        'BBS AI generated an invalid website document.',
      )
    }

    return {
      html,
      source: 'bbs-ai-model',
    }
  }

  return {
    html: fallbackWebsite(request.prompt),
    source: 'fallback',
  }
}
