/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ApiBuilderAuthRouteImport } from './routes/api/builder-auth'
import { Route as ApiBuilderWorkspaceRouteImport } from './routes/api/builder-workspace-old.ts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderAuthRoute = ApiBuilderAuthRouteImport.update({
  id: '/api/builder-auth',
  path: '/api/builder-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderWorkspaceRoute = ApiBuilderWorkspaceRouteImport.update({
  id: '/api/builder-workspace',
  path: '/api/builder-workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/builder-auth': typeof ApiBuilderAuthRoute
  '/api/builder-workspace': typeof ApiBuilderWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/builder-auth': typeof ApiBuilderAuthRoute
  '/api/builder-workspace': typeof ApiBuilderWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/builder-auth': typeof ApiBuilderAuthRoute
  '/api/builder-workspace': typeof ApiBuilderWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builder' | '/api/builder-auth' | '/api/builder-workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/api/builder-auth' | '/api/builder-workspace'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/api/builder-auth'
    | '/api/builder-workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  ApiBuilderAuthRoute: typeof ApiBuilderAuthRoute
  ApiBuilderWorkspaceRoute: typeof ApiBuilderWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder-auth': {
      id: '/api/builder-auth'
      path: '/api/builder-auth'
      fullPath: '/api/builder-auth'
      preLoaderRoute: typeof ApiBuilderAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder-workspace': {
      id: '/api/builder-workspace'
      path: '/api/builder-workspace'
      fullPath: '/api/builder-workspace'
      preLoaderRoute: typeof ApiBuilderWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  ApiBuilderAuthRoute: ApiBuilderAuthRoute,
  ApiBuilderWorkspaceRoute: ApiBuilderWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
